### ISSUE TITLE
conda: command not found

### ISSUE THREAD

**Issue by GJTheurer** [conda-forge/sage-feedstock#101]
I've run into a problem during the installation of SageMath.
After running the WSL install command as administrator I was successful installing Ubutu and setting up a username and password on UNIX.

Following the instructions in the Sage Installation Guide under Windows and No Development I have successfully executed through the command:
$ bash Miniforge3-$(uname(-$uname -m).sh
When I execute the command:
$ conda create -n sage sage python=3.11
I get the error message:
conda: command not found

Can you please help me resolve this?
I am installing on a desktop PC with Windows 11.  After this I will install on a laptop with Windows 10.

Thank you for your help.
Jack

**Comment by skeglingur** [comment]
I had this same issue, I had to install bzip2

`sudo apt install bzip2`

**Comment by GJTheurer** [comment]
Thank you.
Did that and still get:
conda: command not found
Then I tried: sudo apt install conda
and got unable to locate package conda
Maybe I need to install conda somehow, but I don't know how.
Thank you for your help.

**Comment by hearot** [comment]
When you install conda, make sure to type `yes` to all the questions you'll be asked. I was getting the same problem and then I tried answering `yes` to the last question.

**Comment by GJTheurer** [comment]
Thank you.  That works.  That was the problem.
 Best regards,Jack
In a message dated 9/14/2024 10:29:00 AM Eastern Daylight Time, ***@***.*** writes: 

 

When you install conda, make sure to type yes to all the questions you'll be asked. I was getting the same problem and then I tried answering yes to the last question.

**Comment by GJTheurer** [comment]
That was my problem which I solved.
I believe that it's after the command:$ bash Miniforge3-$(uname)-$(uname -m).sh(I believe that was the place)after printing a stream of output it stops at a place waiting for input.The tendency is to just hit Enter, but that will lead to the error.  Instead, you need to type yes at that spot.When the next input prompt appears, do not continue.Instead exit the shell and open Ubuntu again.At that point you should be able to successfully enter:$ conda create -n sage sage python=3.11 The instructions provided are both unclear and incomplete. That's how I fixed it at my end.Good luck.
In a message dated 9/24/2024 10:11:24 AM Eastern Daylight Time, ***@***.*** writes: 

 

hi
I typed yes to all the questions I've been asked and still doesn't work. When I type
$ conda create -n sage sage python=3.11
i get the error message:
conda: command not found

I don't know what to do...

**Comment by david83rm** [comment]
> That was my problem which I solved. I believe that it's after the command:$ bash Miniforge3-$(uname)-$(uname -m).sh(I believe that was the place)after printing a stream of output it stops at a place waiting for input.The tendency is to just hit Enter, but that will lead to the error.  Instead, you need to type yes at that spot.When the next input prompt appears, do not continue.Instead exit the shell and open Ubuntu again.At that point you should be able to successfully enter:$ conda create -n sage sage python=3.11 The instructions provided are both unclear and incomplete. That's how I fixed it at my end.Good luck. In a message dated 9/24/2024 10:11:24 AM Eastern Daylight Time, ***@***.*** writes:    hi I typed yes to all the questions I've been asked and still doesn't work. When I type $ conda create -n sage sage python=3.11 i get the error message: conda: command not found I don't know what to do... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

It worked!! Thank you.
You are right about the instructions.

**Comment by GiorgosP33** [comment]
I tried everything every each one of you said, but I still get "conda: command not found"
What can I do?

**Comment by trevorkarn** [comment]
What happens when you type ‘conda —version’?

**Comment by GiorgosP33** [comment]
conda 24.7.1

**Comment by GiorgosP33** [comment]
What can i do , if someone can help me?

**Comment by GiorgosP33** [comment]
This 'What happens when you type ‘conda —version’?' save me thanks.

**Comment by 2lbOne** [comment]
I also encounter this annoying problem and it might be helpful to check this page [https://stackoverflow.com/questions/53805965/windows-subsystem-for-linux-conda-command-not-found](url) on stackoverflow.

As conda would be installed in home/{your user name}/miniforge3 by defult, type cd home/{your user name}/miniforge3/bin and run, then run ./conda init. And remember to replace {your user name} with your user name in wsl2.
Reopen the console and you could see there is a (base) before the user name like "(base) yourusername@computername:~$", then conda command can be used.

And as [hearot](https://github.com/hearot) said, just simply reinstall again and answer yes for all questions, especially for the last question which asks "Do you wish to update your shell profile to automatically initialize conda? blablabla~~~ You can undo this by running `conda init --reverse $SHELL`? [yes|no]" , then things should be done.

**Comment by saraedum** [comment]
I believe the original issue has been resolved. So I am closing this one.
